package com.mojang.minecraft;

public enum Setting {
    MUSIC, SOUND, INVERT_MOUSE, SHOW_DEBUG, RENDER_DISTANCE, VIEW_BOBBING, LIMIT_FRAMERATE, SMOOTHING, ANISOTROPIC, ALLOW_SERVER_TEXTURES, SPEEDHACK_TYPE, FONT_SCALE, ENABLE_HACKS, SHOW_NAMES
}
